services:

# ┌──────────────────────────────────────────────────┐
# │                        VPS                       │
# └──────────────────────────────────────────────────┘

# ────────── CADDY ──────────

  caddy:
    image: caddy:2.11.2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - internal

# ────────── AUTHELIA ──────────

  authelia:
    image: authelia/authelia:4.39
    container_name: authelia
    restart: unless-stopped
    volumes:
      - ./authelia:/config
    networks:
      - internal

# ────────── WIREGUARD ──────────

  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SERVERURL=auto
      - SERVERPORT=51820
      - PEERS=padre,raspberry
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.0.0.0/24
      - ALLOWEDIPS=10.0.0.0/24
    volumes:
      - ./wireguard:/config
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      - "2022:22"
      - "2023:2023"
      - "5900:5900"
      - 40000-40100:40000-40100/udp
      - "47984:47984/tcp"
      - "47989:47989/tcp"
      - "48010:48010/tcp"
      - "47998-48000:47998-48000/udp"
      - "48002:48002/udp"
      - "48004:48004/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - internal

# ────────── PORTAINER ──────────

  portainer:
    image: portainer/portainer-ce:2.39.0
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - internal

# ────────── UPTIME KUMA ──────────

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - uptime-kuma_data:/app/data
    environment:
      - UPTIME_KUMA_DISABLE_AUTH=1
    restart: unless-stopped
    networks:
      - internal

# ────────── GUACAMOLE ──────────

  postgres:
    image: postgres:16.9-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=guacamole_db
      - POSTGRES_USER=guacamole_user
      - POSTGRES_PASSWORD=guacamole_pass
    volumes:
      - guacamole_postgres_data:/var/lib/postgresql/data
      - ./guacamole/:/docker-entrypoint-initdb.d:ro
    networks:
      - internal

  guacd:
    image: guacamole/guacd:1.6.0
    container_name: guacd
    restart: unless-stopped
    network_mode: "service:wireguard"
    depends_on:
      - wireguard

  guacamole:
    image: guacamole/guacamole:1.6.0
    container_name: guacamole
    restart: unless-stopped
    environment:
      - GUACD_HOSTNAME=wireguard
      - GUACD_PORT=4822
      - GUACAMOLE_HOME=/etc/guacamole
      - SERVER_PORT=8080
      - POSTGRESQL_HOSTNAME=postgres
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DATABASE=guacamole_db
      - POSTGRESQL_USERNAME=guacamole_user
      - POSTGRESQL_PASSWORD=guacamole_pass
      - HTTP_AUTH_HEADER=Remote-User
      - HTTP_AUTH_AUTO_CREATE_ACCOUNTS=true
      - QUICKCONNECT_ENABLED=false
      - BAN_ENABLED=true
    networks:
      - internal
    depends_on:
      - postgres
      - guacd

# ────────── FILE BROWSER ──────────

  filebrowser-vps:
    image: filebrowser/filebrowser:v2.44.0
    container_name: filebrowser-vps
    restart: unless-stopped
    environment:
      - FB_NOAUTH=true
      - FB_ROOT=/srv
      - FB_DATABASE=/tmp/database.db
      - FB_PORT=8085
    volumes:
      - ~/:/srv
      - filebrowser_config:/config
      - filebrowser_database:/database
    networks:
      - internal

# ────────── NAVIDROME ──────────

  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
    volumes:
      - navidrome_data:/data
      - "./navidrome:/music:ro"
    networks:
      - internal

# ────────── ROMM ──────────

  romm:
    image: rommapp/romm:latest
    container_name: romm
    restart: unless-stopped
    depends_on:
      - romm-db
    environment:
      - DB_HOST=romm-db
      - DB_NAME=romm
      - DB_USER=romm_user
      - DB_PASSWD=romm_pass
      - ROMM_AUTH_SECRET_KEY=
      - IGDB_CLIENT_ID=
      - IGDB_CLIENT_SECRET=
    volumes:
      - romm_config:/romm/config
      - romm_assets:/romm/assets
      - romm_redis_data:/redis-data
      - romm_library_data:/romm/library
      - romm_resources_data:/romm/resources
      - ./romm:/romm/library/roms
    networks:
      - internal

  romm-db:
    image: mariadb:latest
    container_name: romm-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_DATABASE=romm
      - MYSQL_USER=romm_user
      - MYSQL_PASSWORD=romm_pass
    volumes:
      - romm_database:/var/lib/mysql
    networks:
      - internal

# ────────── OPEN WEBUI ──────────

  openwebui:
    image: ghcr.io/open-webui/open-webui:v0.9.2
    container_name: openwebui
    restart: unless-stopped
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    environment:
      - HOST=0.0.0.0
      - PORT=8081
      - WEBUI_URL=https://openwebui.mydomain.net
      - ENABLE_LOGIN_FORM=False
      - ENABLE_SIGNUP=False
      - ENABLE_OPENAI_API=False
      - WEBUI_AUTH_TRUSTED_EMAIL_HEADER=Remote-Email
      - WEBUI_AUTH_TRUSTED_NAME_HEADER=Remote-Name
      - WEBUI_AUTH_TRUSTED_GROUPS_HEADER=Remote-Groups
      - OLLAMA_BASE_URL=10.0.0.2:11434
    volumes:
      - openwebui_data:/app/backend/data

# ────────── SEARXNG ──────────

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    volumes:
      - searxng_cache:/var/cache/searxng
      - ./searxng:/etc/searxng
    environment:
      - SEARXNG_PORT=8888
      - SEARXNG_BASE_URL=https://searxng.mydomain.net/
    networks:
      - internal

# ────────── FRONT ──────────

  front:
    container_name: front
    restart: unless-stopped
    build:
      context: ./dashboard/front
      dockerfile: Dockerfile
      args:
        - VITE_PORTAINER_DOMAIN=portainer.mydomain.net
        - VITE_UPTIME_KUMA_DOMAIN=kuma.mydomain.net
        - VITE_GUACAMOLE_DOMAIN=guacamole.mydomain.net
        - VITE_FILEBROWSER_VPS_DOMAIN=files.vps.mydomain.net
        - VITE_NAVIDROME_DOMAIN=navidrome.mydomain.net
        - VITE_ROMM_DOMAIN=romm.mydomain.net
        - VITE_FILEBROWSER_RPI_DOMAIN=files.rpi.mydomain.net
        - VITE_TORRENT_RPI_DOMAIN=torrent.rpi.mydomain.net
        - VITE_FILEBROWSER_PC_DOMAIN=files.pc.mydomain.net
        - VITE_VSCODE_PC_DOMAIN=vscode.mydomain.net
        - VITE_NAVIDROME_PC_DOMAIN=navidrome.pc.mydomain.net
        - VITE_JELLYFIN_PC_DOMAIN=jellyfin.mydomain.net
        - VITE_TORRENT_PC_DOMAIN=torrent.mydomain.net
        - VITE_SUNSHINE_PC_DOMAIN=sunshine.mydomain.net
        - VITE_MOONLIGHT_PC_DOMAIN=moonlight.mydomain.net
        - VITE_ACESTEP_DOMAIN=acestep.mydomain.net
        - VITE_COMFYUI_DOMAIN=comfyui.mydomain.net
        - VITE_OPENWEBUI_DOMAIN=openwebui.mydomain.net
    networks:
      - internal

# ────────── API ──────────

  api:
    container_name: api
    restart: unless-stopped
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    build:
      context: ./dashboard/api
      dockerfile: Dockerfile
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    environment:
      - ADMIN_USER=guaca_admin
      - ADMIN_PASS=guaca_pass
      - GUAC_URL=GUAC_URL=http://guacamole:8080/guacamole
      - GUAC_PUBLIC_URL=https://guacamole.mydomain.net/guacamole
      - NODE_ENV=production
      - PORT=4000
      - PC_IP=10.0.0.2
      - RPI_IP=10.0.0.3
      - SSH_USER_PC=user_pc
      - SSH_USER_RPI=user_rpi
      - TELEMETRY_PC_PORT=8000
      - TELEMETRY_RPI_PORT=8000

networks:
  internal:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  portainer_data:
  uptime-kuma_data:
  navidrome_data:
  openwebui_data:
  searxng_cache:
  guacamole_postgres_data:
  filebrowser_config:
  filebrowser_database:
  romm_config:
  romm_assets:
  romm_database:
  romm_redis_data:
  romm_library_data:
  romm_resources_data:
